spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/antennadb
    password: root
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL8Dialect
          storage_engine: innodb
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
debug: 'true'
